package user.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "customers")
public class Customer extends User {

    private boolean premiumSubscription;

    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name = "user_groups", joinColumns = {
        @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false, updatable =
            false)
        }, inverseJoinColumns = {
        @JoinColumn(name = "group_id", referencedColumnName = "groupId", nullable = false,
            updatable = false)
    })
    @JsonBackReference
    @JsonIgnoreProperties("groupMembers")
    private List<Group> groupsForTeamSports;


    public Customer() {
    }

    /**
     * Constructor without id (generated by Spring JPA).
     *
     * @param username            - String
     * @param password            - String
     * @param premiumSubscription - boolean
     */
    public Customer(String username, String password, boolean premiumSubscription) {
        super(username, password);
        this.premiumSubscription = premiumSubscription;
    }

    /**
     * Constructor with id.
     */
    public Customer(long id, String username, String password, boolean premiumSubscription,
                    List<Group> groupsForTeamSports) {
        super(id, username, password);
        this.premiumSubscription = premiumSubscription;
        this.groupsForTeamSports = groupsForTeamSports;
    }

    public boolean isPremiumUser() {
        return premiumSubscription;
    }

    public void setPremiumUser(boolean premiumUser) {
        this.premiumSubscription = premiumUser;
    }

    public List<Group> getGroupsForTeamSports() {
        return groupsForTeamSports;
    }

    public void setGroupsForTeamSports(List<Group> groupsForTeamSports) {
        this.groupsForTeamSports = groupsForTeamSports;
    }

//    public boolean isPremiumSubscription() {
//        return premiumSubscription;
//    }

//    public void setPremiumSubscription(boolean premiumSubscription) {
//        this.premiumSubscription = premiumSubscription;
//    }

    public void addGroupToUsersGroupList(Group group) {
        if(!groupsForTeamSports.contains(group)){
            this.groupsForTeamSports.add(group);
            group.setGroupSize(group.getGroupSize() + 1);
        }
        else{
            throw new IllegalStateException("customer with id " + this.getId() + " already exists in the group!");
        }
    }


    @Override
    public String toString() {
        String res = "Customer{" +
                "id=" + super.getId() +
                ", username='" + super.getUsername() + '\''
                + ", password" + "='" + super.getPassword() + "', ";

        if(!groupsForTeamSports.isEmpty()) {
            res = res + " groups = {";
            for(Group g : groupsForTeamSports) {
                res = res + "'" + g.getGroupName() + "'" + ",";
            }
            res = res + "}";
            return res;
        }
        return res + "}";
    }


}
